export default {
  home: '首页',
  discover: '发现',
  askDoctor: '问医生',
  inbox: '消息',
  profile: '我的',
  adTitle1:
    '【热拉提】热拉提plus+复合水光（3ml菲洛嘉+2ml润月雅），一提一嫩，老态拜拜',
  adClinic1: '清华大学玉泉医院',
  adOriPrice1: '5800',
  adNewPrice1: '2800',
  adPlace1: '吉隆坡',
  adTitle2: '【玻尿酸】原装进口 【伊婉C玻尿酸1ml】足量注射 不收取注射费',
  adClinic2: '北京禾美嘉医疗整形',
  adOriPrice2: '3200',
  adNewPrice2: '1688',
  adPlace2: '加影',
  adTitle3:
    '【除皱瘦脸】【进口除皱针】单部位 祛除鱼尾纹/川字纹/抬头纹/眼周细纹 瘦脸塑形小V脸',
  adClinic3: '北京爱悦丽格医疗美容',
  adOriPrice3: '9999',
  adNewPrice3: '8888',
  adPlace3: '太平',
  adTitle4:
    '【半永久纹眉】性价比超高/销量爆款/绣眉/美瞳线立体仿生线条眉/立体裸妆定制，不结痂，纯植',
  adClinic4: '北京英煌医疗美容',
  adOriPrice4: '7900',
  adNewPrice4: '6888',
  adPlace4: '怡保',
};
