export default {
  home: 'Home',
  discover: 'Discover',
  askDoctor: 'Ask Doctor',
  inbox: 'Inbox',
  profile: 'My Profile',
  adTitle1: 'Facial Treatment Essence (Pitera™ Essence)',
  adClinic1: 'Kuala Lumpur Hospital',
  adOriPrice1: '5800',
  adNewPrice1: '2800',
  adPlace1: 'KL',
  adTitle2: 'First Experience Kit',
  adClinic2: 'Kuala Lumpur Hospital',
  adOriPrice2: '3200',
  adNewPrice2: '1688',
  adPlace2: 'Kajang',
  adTitle3: 'GenOptics Aura Essence Serum',
  adClinic3: 'Prince Court Medical Centre',
  adOriPrice3: '9999',
  adNewPrice3: '8888',
  adPlace3: 'Taiping',
  adTitle4: 'SKINPOWER Cream',
  adClinic4: 'Pantai Hospital Cheras',
  adOriPrice4: '7900',
  adNewPrice4: '6888',
  adPlace4: 'Ipoh',
  myBooking: 'My Booking',
  writeDiary: 'Write Diary',
  blogging: 'Blogging',
  askQuestion: 'Ask Question',
  applyCert: 'Apply For Certification',
  logout: 'Logout',
  yes: 'YES',
  cancel: 'Cancel',
};
