export default {
  malaysia: 'Malaysia',
  faceLift: 'Face Lift',
  hyaluronicAcid: 'Hyaluronic\nAcid',
  breasts: 'Breasts',
  eye: 'Eye',
  nose: 'Nose',
  dentalBeauty: 'Dental\nBeauty',
  skinBeauty: 'Skin\nBeauty',
  fatFilling: 'Fat\nFilling',
  hairGrowth: 'Hair\nGrowth',
  laserHairRemoval: 'Laser Hair Removal',
  ear: 'Ear',
  privateSurgery: 'Private Plasic\nSurgery',
  facialContour: 'Facial\nContour',
  bodyShaping: 'Body\nShaping',
  lipSurgery: 'Lip\nSurgery',
  semiMakeup: 'Semi-Permanent Makeup',
  medicalHealth: 'Medical\nHealth',
  antiAging: 'Anti-Aging',
  other: 'Other',
  mirrorFaceMeasurement: 'Mirror Face Measurement',
  threeDImage: '3D\nImage',
  starFace: 'Star\nFace',
  skinDetection: 'Skin\nDetection',
  proOrganizations: 'Professional Organizations',
  eliteDoctors: 'Elite Doctors',
  popular: 'Popular',
};
